- platform: snmp
  icon: mdi:invert-colors
  name: 'Cyan Level'
  host: !secret printer_host
  baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.2
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{((value | int)) | int}}'
- platform: snmp
  name: 'Magenta Level'
  host: !secret printer_host
  baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.3
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{((value | int)) | int}}'
- platform: snmp
  name: 'Yellow Level'
  host: !secret printer_host
  baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.4
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{((value | int)) | int}}'
- platform: snmp
  name: 'Key Level'
  host: !secret printer_host
  baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.1
  accept_errors: true
  unit_of_measurement: '%'
  value_template: '{{((value | int)) | int}}'

- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: 'Cyan'
      unit_of_measurement: '%'
      value_template: '{{ value }}'
      group_function: last
      where: '"entity_id" = ''cyan_level'''
      measurement: '"%"'
      field: value
      database: !secret influxdb_database
    - name: 'Magenta'
      unit_of_measurement: '%'
      value_template: '{{ value }}'
      group_function: last
      where: '"entity_id" = ''magenta_level'''
      measurement: '"%"'
      field: value
      database: !secret influxdb_database
    - name: 'Yellow'
      unit_of_measurement: '%'
      value_template: '{{ value }}'
      group_function: last
      where: '"entity_id" = ''yellow_level'''
      measurement: '"%"'
      field: value
      database: !secret influxdb_database
    - name: 'Key'
      unit_of_measurement: '%'
      value_template: '{{ value }}'
      group_function: last
      where: '"entity_id" = ''key_level'''
      measurement: '"%"'
      field: value
      database: !secret influxdb_database