- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - temp_high_record_c
    - temp_high_1d_c
    - temp_c
    - temp_low_1d_c
    - temp_low_record_c
    - precip_1d
    - relative_humidity
    - pressure_mb
#    - precip_1d_mm
    - wind_kph
#    - wind_1d_kph
    - alerts
- platform: systemmonitor
  resources:
    - type: processor_use
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
